skip_tags: true

version: 2.0.{build}

image: Ubuntu2004

init:
    - git config --global core.autocrlf input

install:
  - sh: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sh: sudo dpkg -i packages-microsoft-prod.deb
  - sh: rm packages-microsoft-prod.deb
  - sh: sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0

build_script:
    - git submodule init
    - git submodule update
    - cd Azurite
    - npm ci
    - npm run build
    - npm install -g
    - (exec azurite -l ~/.data &)
    - sleep 5
    - cd ..
    - dotnet tool restore
    - dotnet nake pack

artifacts:
- path: Artifacts\Release\*.nupkg
