version: 2.0.'{build}'

image: Ubuntu

build_script:
    - git submodule init
    - git submodule update
    - cd Azurite
    - npm ci
    - npm run build
    - npm install -g
    - azurite -l ~/.data
    - cd ..
    - Nake.bat AppVeyor=true pack

test: off

artifacts:
- path: Artifacts\Release\*.nupkg
